### PR TITLE
Use assertEqual instead of assertEquals for Python 3.11 compatibility.

### PR DESCRIPTION
**Pull request by tirkarthi**
Ref : https://github.com/python/cpython/pull/28268

### CODE REVIEW

**Comment by spyoungtech** [comment]
Thanks for this. Merged!

**Comment by tirkarthi** [comment]
Thanks @spyoungtech

**Review by Irischka991620 — COMMENTED** [review]
- [ ]

**Comment by Irischka991620** [comment]
Google

**Pull request merged**
